# Собираем тройные кавычки динамически, чтобы парсер чата не сошел с ума
TICK = "`" * 3

lines = [
    "# 📖 Phonebook Hybrid Test Automation Framework\n\n",
    "[![Phonebook UI Tests](https://github.com/warmanofmars-star/QA3553_Phonebook/actions/workflows/tests.yml/badge.svg)](https://github.com/warmanofmars-star/QA3553_Phonebook/actions)\n",
    "📊 **Live Allure Report:** [View Dashboard](https://warmanofmars-star.github.io/QA3553_Phonebook/)\n\n",
    "Robust, production-ready hybrid test automation framework for the \"Phonebook\" web application.\n",
    "This project demonstrates a **Senior-level approach** to QA automation, combining classic UI testing, API integration, and modern tools to ensure fast, stable, and secure test execution.\n\n",
    "## 🛠 Technologies & Tools\n",
    "* **Language:** Python 3.12+\n",
    "* **UI Frameworks:** Selenium WebDriver 4+, Playwright (Sync API)\n",
    "* **API Testing:** Requests\n",
    "* **Test Runner:** Pytest (with `pytest-xdist` for parallel execution)\n",
    "* **Design Pattern:** Page Object Model (POM)\n",
    "* **Test Data:** Faker (dynamic generation of names, phones, emails)\n",
    "* **Reporting:** Allure Report (with secure data masking)\n",
    "* **CI/CD:** GitHub Actions (Automated runs with Headless browser execution)\n",
    "* **Notifications:** Telegram Bot API\n",
    "* **Security:** `python-dotenv` for managing sensitive credentials\n\n",
    "## 🚀 Key Architectural Features\n\n",
    "* **Hybrid Testing Approach (API + UI):** Tests use API calls to set up preconditions (e.g., creating a contact) and teardown data, drastically reducing UI test execution time and ensuring test isolation.\n",
    "* **Dual Framework Support:** Implemented primarily using **Selenium** with an integrated **Playwright** module to demonstrate modern tool capabilities and auto-waiting concepts.\n",
    "* **Smart Browser Cascading:** The framework automatically detects the environment. It runs headless Google Chrome in CI/CD (GitHub Actions) for consistency, but gracefully falls back to Microsoft Edge for local execution if Chrome is unavailable.\n",
    "* **Security & Log Masking:** Sensitive data (passwords, auth tokens) are strictly masked (********) in all console outputs, test logs, and Allure step reports.\n",
    "* **Thread-Safe Custom Logging:** Features a proprietary logging utility with dual-stream outputs. It provides real-time, ANSI-colored console logs for local debugging and simultaneously writes clean, thread-safe logs to individual files via Process IDs (`PID`), ensuring stable log capture during parallel execution (`pytest-xdist`).\n",
    "* **Advanced Data Modeling:** Implements Python `@dataclass` for representing test entities, allowing for clean object instantiation and dynamic payload overriding.\n\n",
    "## ⚙️ Setup & Installation\n\n",
    "### 1. Clone and Setup\n",
    f"{TICK}bash\n",
    "git clone https://github.com/warmanofmars-star/QA3553_Phonebook.git\n",
    "cd QA3553_Phonebook\n",
    "python -m venv .venv\n",
    "source .venv/Scripts/activate  # For Windows: .venv\\Scripts\\activate\n",
    "pip install -r requirements.txt\n",
    "playwright install chromium\n",
    f"{TICK}\n\n",
    "### 2. Environment Variables (.env)\n",
    "Create a `.env` file in the root directory and add your valid test user credentials:\n",
    f"{TICK}env\n",
    "HEADLESS_MODE=false\n",
    "ALLOW_MASS_DELETE=false\n",
    "USER_EMAIL=your_valid_email@gmail.com\n",
    "USER_PASSWORD=Your_Valid_Password123$\n",
    "BASE_URL=https://telranedu.web.app\n",
    "API_URL=https://contactapp-telran-backend.herokuapp.com\n",
    f"{TICK}\n\n",
    "## 🏃‍♂️ How to Run Tests\n\n",
    "**Run all hybrid tests (Selenium UI + API) in parallel:**\n",
    f"{TICK}bash\n",
    "pytest tests/ -n auto --clean-alluredir --alluredir=allure-results\n",
    f"{TICK}\n\n",
    "**Run modern Playwright tests (headed mode for debugging):**\n",
    f"{TICK}bash\n",
    "pytest tests/test_playwright_login.py -s --headed\n",
    f"{TICK}\n\n",
    "**Generate and view Allure Report locally:**\n",
    f"{TICK}bash\n",
    "allure serve allure-results\n",
    f"{TICK}\n\n",
    "## ☁️ CI/CD & Remote Execution\n",
    "This project is fully integrated with **GitHub Actions**. \n",
    "* On every manual trigger (`workflow_dispatch`), the pipeline spins up an Ubuntu runner, installs Chrome, and executes the test suite in parallel Headless mode.\n",
    "* It securely accesses credentials via **GitHub Secrets**.\n",
    "* Automatically uploads Log archives as workflow artifacts.\n",
    "* Generates an Allure report, deploys it to **GitHub Pages**, and sends a notification with the link to Telegram.\n\n",
    "## 🏗 Project Structure\n",
    f"{TICK}text\n",
    "QA3553_Phonebook/\n",
    "├── .github/workflows/    # CI/CD pipeline configuration (tests.yml)\n",
    "├── api_tests/            # Pure API test suites\n",
    "├── data/                 # Test data generators (Faker, DataClasses)\n",
    "├── models/               # Data models (Contact, User)\n",
    "├── pages/                # Page Object classes (Selenium BasePage & Playwright PwBasePage)\n",
    "├── tests/                # Hybrid and UI Test suites\n",
    "├── utils/                # Custom logger, WebDriver listener, API helpers\n",
    "├── logs/                 # Auto-rotating, thread-safe local log files\n",
    "├── conftest.py           # Pytest fixtures, Smart Browser Cascading, API Setup\n",
    "├── requirements.txt      # Project dependencies\n",
    "└── README.md             # Project documentation\n",
    f"{TICK}\n\n",
    "---\n",
    "*Author: Maksim Vinogradov*\n"
]

with open("README.md", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("✅ Файл README.md успешно перезаписан! Можно пушить.")