# Собираем тройные кавычки динамически, чтобы парсер чата не сошел с ума
TICK = "`" * 3

lines = [
    "# 📖 Phonebook Hybrid Test Automation Framework\n\n",
    "[![UI Tests in Docker](https://github.com/warmanofmars-star/QA3553_Phonebook/actions/workflows/tests.yml/badge.svg)](https://github.com/warmanofmars-star/QA3553_Phonebook/actions)\n",
    "📊 **Live Allure Report:** [View Dashboard](https://warmanofmars-star.github.io/QA3553_Phonebook/)\n\n",
    "Robust, production-ready hybrid test automation framework for the \"Phonebook\" web application, ",
    "featuring a fully containerized **Infrastructure as Code (IaC)** approach.\n\n",
    "This project demonstrates a **Senior-level approach** to QA automation, combining classic UI testing, API integration, ",
    "remote browser execution via Selenoid, and modern container orchestration.\n\n",
    "## 🛠 Technologies & Tools\n",
    "* **Language:** Python 3.12+\n",
    "* **UI Frameworks:** Selenium WebDriver 4+, Playwright (Sync API)\n",
    "* **API Testing:** Requests\n",
    "* **Containerization & Orchestration:** Docker, Docker Compose, Selenoid (with video-recorder)\n",
    "* **Test Runner:** Pytest (with `pytest-xdist` for parallel execution)\n",
    "* **Design Pattern:** Page Object Model (POM)\n",
    "* **Test Data:** Faker (dynamic generation of names, phones, emails)\n",
    "* **Reporting:** Allure Report (with embedded test session videos and secure data masking)\n",
    "* **CI/CD:** GitHub Actions (Fully containerized pipeline execution)\n",
    "* **Notifications:** Telegram Bot API\n",
    "* **Security:** `python-dotenv` for managing sensitive credentials\n\n",
    "## 🚀 Key Architectural Features\n\n",
    "* **Dockerized Infrastructure (IaC):** The entire test environment—including the framework, Selenoid hub, Chrome instances, and video recording modules—is orchestrated via Docker Compose, guaranteeing absolute environment consistency across local machines and CI/CD.\n",
    "* **Isolated Networking & Named Volumes:** Utilizes a custom bridge network (`qa-network`) for seamless container communication and persistent `video-data` named volumes to handle test artifacts independently of host OS file systems.\n",
    "* **Automatic Video Attachment:** Every test execution session is recorded via FFmpeg/Selenoid, and the resulting `.mp4` files are automatically attached to the Allure report upon teardown.\n",
    "* **Hybrid Testing Approach (API + UI):** Tests use API calls to set up preconditions and manage state, drastically reducing execution time and ensuring test isolation.\n",
    "* **Smart Browser Cascading:** Automatically detects runtime context (Docker vs. local execution) and supports fallback mechanisms for local debugging.\n",
    "* **Security & Log Masking:** Sensitive data (passwords, tokens) are strictly masked in all logs and Allure reports.\n",
    "* **Thread-Safe Custom Logging:** Proprietary logging utility with dual-stream outputs, ANSI-colored console logs, and individual log files per Process ID (`PID`) for safe parallel execution (`pytest-xdist`).\n\n",
    "## ⚙️ Setup & Installation\n\n",
    "### 1. Clone and Setup\n",
    f"{TICK}bash\n",
    "git clone https://github.com/warmanofmars-star/QA3553_Phonebook.git\n",
    "cd QA3553_Phonebook\n",
    "python -m venv .venv\n",
    "source .venv/Scripts/activate  # For Windows: .venv\\Scripts\\activate\n",
    "pip install -r requirements.txt\n",
    "playwright install chromium\n",
    f"{TICK}\n\n",
    "### 2. Environment Variables (.env)\n",
    "Create a `.env` file in the root directory and add your credentials:\n",
    f"{TICK}env\n",
    "HEADLESS_MODE=false\n",
    "ALLOW_MASS_DELETE=false\n",
    "USER_EMAIL=your_valid_email@gmail.com\n",
    "USER_PASSWORD=Your_Valid_Password123$\n",
    "BASE_URL=https://telranedu.web.app\n",
    "API_URL=https://contactapp-telran-backend.herokuapp.com\n",
    f"{TICK}\n\n",
    "## 🏃‍♂️ How to Run Tests\n\n",
    "**Run tests in the isolated Docker container (Recommended):**\n",
    f"{TICK}bash\n",
    "docker-compose up --build --exit-code-from qa-framework\n",
    f"{TICK}\n\n",
    "**Run locally via Pytest (parallel execution):**\n",
    f"{TICK}bash\n",
    "pytest tests/ -n auto --clean-alluredir --alluredir=allure-results\n",
    f"{TICK}\n\n",
    "**Generate and view Allure Report locally:**\n",
    f"{TICK}bash\n",
    "allure serve allure-results\n",
    f"{TICK}\n\n",
    "## ☁️ CI/CD & Remote Execution\n",
    "The project features an advanced **GitHub Actions** pipeline:\n",
    "* Automatically triggers on `main` branch pushes or manual dispatch (`workflow_dispatch`).\n",
    "* Spins up a clean Linux runner, builds the Docker Compose stack, and executes all tests in parallel.\n",
    "* Securely injects credentials via **GitHub Secrets**.\n",
    "* Generates and deploys the Allure report to **GitHub Pages**.\n",
    "* Sends automated execution status notifications with a direct link to Telegram.\n\n",
    "## 🏗 Project Structure\n",
    f"{TICK}text\n",
    "QA3553_Phonebook/\n",
    "├── .github/workflows/    # CI/CD pipeline configuration (tests.yml)\n",
    "├── api_tests/            # Pure API test suites\n",
    "├── data/                 # Test data generators (Faker, DataClasses)\n",
    "├── models/               # Data models (Contact, User)\n",
    "├── pages/                # Page Object classes (Selenium BasePage & Playwright PwBasePage)\n",
    "├── selenoid/             # Selenoid configuration (browsers.json)\n",
    "├── tests/                # Hybrid and UI Test suites\n",
    "├── utils/                # Custom logger, WebDriver listener, API helpers\n",
    "├── logs/                 # Auto-rotating, thread-safe local log files\n",
    "├── conftest.py           # Pytest fixtures, Selenoid remote connection, video attachment hooks\n",
    "├── Dockerfile            # Container definition for the test framework\n",
    "├── docker-compose.yml    # Infrastructure orchestration (Selenoid + Framework + Network + Volumes)\n",
    "├── requirements.txt      # Project dependencies\n",
    "└── README.md             # Project documentation\n",
    f"{TICK}\n\n",
    "---\n",
    "*Author: Maksim Vinogradov*\n"
]

with open("README.md", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("✅ Файл README.md успешно перезаписан!")