name: Phonebook UI Tests

on:
  workflow_dispatch:
      inputs:
        allow_mass_delete:
          description: 'Включить полное удаление всех контактов (DANGER!)'
          required: false
          type: boolean
          default: false

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Скачиваем код проекта
        uses: actions/checkout@v4

      - name: Подготавливаем переменные окружения для Docker
        run: |
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> .env
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> .env
          echo "ALLOW_MASS_DELETE=${{ github.event.inputs.allow_mass_delete }}" >> .env

      # 👇 ДОБАВЛЯЕМ ПРЕДВАРИТЕЛЬНУЮ ЗАГРУЗКУ ОБРАЗА БРАУЗЕРА ДЛЯ СЕЛЕНОИДА
      - name: Pull Selenoid Chrome image
        run: docker pull selenoid/chrome:128.0

      - name: Запускаем автотесты в изолированной среде Docker Compose
        run: docker compose up --build --exit-code-from qa-framework
        continue-on-error: true

      - name: Устанавливаем Allure CLI и генерируем отчет
        if: always()
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results -o allure-report --clean

      - name: Публикуем отчет на GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Отправляем уведомление в Telegram
        uses: appleboy/telegram-action@master
        if: always()
        with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              🤖 Автотесты Phonebook завершены (Docker Environment)!
              📊 Посмотреть Allure-отчет можно по ссылке:
              👉 https://warmanofmars-star.github.io/QA3553_Phonebook/