name: Phonebook UI Tests

on:
  workflow_dispatch:
      inputs:
        allow_mass_delete:
          description: 'Включить полное удаление всех контактов (DANGER!)'
          required: false
          type: boolean
          default: false

jobs:
  test:
    runs-on: ubuntu-22.04
    # 👇 НАША МАТРИЦА КРОССБРАУЗЕРНОСТИ
    strategy:
      fail-fast: false # Если Chrome упадет, мы всё равно хотим дождаться результатов Firefox
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Скачиваем код проекта
        uses: actions/checkout@v4

      - name: Подготавливаем переменные окружения для Docker
        run: |
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> .env
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> .env
          echo "ALLOW_MASS_DELETE=${{ github.event.inputs.allow_mass_delete }}" >> .env

      # 👇 СКАЧИВАЕМ VNC-ОБРАЗЫ ОБЕИХ ВЕРСИЙ (с поддержкой видео)
      - name: Pull Selenoid Browser Images & Video Recorder
        run: |
          docker pull selenoid/vnc_chrome:128.0
          docker pull selenoid/vnc_firefox:125.0
          docker pull selenoid/video-recorder:latest-release

      # 👇 ПРОКИДЫВАЕМ ТЕКУЩИЙ БРАУЗЕР ИЗ МАТРИЦЫ ВНУТРЬ ДОКЕРА
      - name: Запускаем автотесты в изолированной среде Docker Compose
        env:
          BROWSER: ${{ matrix.browser }}
        run: docker compose up --build --exit-code-from qa-framework
        continue-on-error: true

      - name: Создаем файл окружения для Allure
        if: always()
        run: |
          sudo chown -R $USER:$USER allure-results
          echo "Browser=${{ matrix.browser }}" >> allure-results/environment.properties
          echo "Environment=Docker Compose (Selenoid)" >> allure-results/environment.properties
          echo "CI=GitHub Actions" >> allure-results/environment.properties

      - name: Устанавливаем Allure CLI и генерируем отчет
        if: always()
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results -o allure-report --clean

      - name: Публикуем отчет на GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Отправляем уведомление в Telegram
        uses: appleboy/telegram-action@master
        if: always()
        with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              🤖 Автотесты Phonebook завершены!
              🌐 Браузер: ${{ matrix.browser }}
              📊 Посмотреть Allure-отчет можно по ссылке:
              👉 https://warmanofmars-star.github.io/QA3553_Phonebook/